/**
 * The device's half of answering (roadmap S-03, PRD FR-004/FR-019).
 *
 * Owns the per-question clock and the two requests, so `index.astro`'s script stays one
 * state machine rather than growing a second one beside it.
 *
 * May not value-import from `src/quiz/` or `src/lib/session/`, and may not read
 * `import.meta.env` (`boundary.test.ts`). The storage key arrives through `define:vars`,
 * exactly as `PLAYER_STORAGE_KEY` does for `player.ts`.
 *
 * Nothing here throws — `player.ts`'s posture, and for the same reason: Safari in
 * private mode throws on a storage write, storage can be disabled outright, and a phone
 * on a venue network loses requests. None of that may take the view down mid-question.
 */

export type SubmitOutcome =
  | { outcome: "accepted" }
  /**
   * The server refused, with a Polish message the view renders directly. Kept apart
   * from `failed` because the two mean opposite things to an attendee: this one is an
   * answer about their answer, the other is "we do not know".
   */
  | { outcome: "rejected"; error: string }
  | { outcome: "failed" };

export type OwnResult = {
  readonly answered: boolean;
  readonly correct: boolean | null;
  readonly awarded: number | null;
  readonly total: number;
};

/** What the seen-question store holds: question id → first-paint epoch ms. */
type SeenMap = Record<string, number>;

function readSeen(storageKey: string): SeenMap {
  try {
    const raw = window.localStorage.getItem(storageKey);
    if (raw === null) return {};

    const parsed: unknown = JSON.parse(raw);
    if (typeof parsed !== "object" || parsed === null) return {};

    const map: SeenMap = {};
    for (const [questionId, value] of Object.entries(parsed as Record<string, unknown>)) {
      if (typeof value === "number" && Number.isFinite(value) && value > 0) {
        map[questionId] = value;
      }
    }
    return map;
  } catch {
    return {};
  }
}

/**
 * The first moment this device painted this question, in epoch milliseconds.
 *
 * **This is the reload fix, and it is the whole reason the value is persisted.** FR-019
 * measures the speed component from when the question became visible on *this* device.
 * Held only in memory, that timestamp is regenerated by a reload — and a reload during a
 * fifteen-minute segment is near-certain — so reloading mid-question would hand out full
 * speed weight, to anyone who did it deliberately and to anyone who did it by accident.
 *
 * Reads back an existing value rather than overwriting it. Called on every paint of the
 * question, so it must be idempotent.
 *
 * **The residual is accepted and named**: a device that clears storage, and an attendee
 * who joins after the question opened, both start their clock now. FR-019 says the clock
 * is the device's, and a latecomer genuinely did just see the question.
 *
 * Unavailable storage degrades to "the clock starts now" — the same silent-failure
 * posture `writePlayer` takes, because a storage quirk must not stop an attendee
 * answering.
 */
export function markSeen(storageKey: string, questionId: string, now = Date.now()): number {
  const seen = readSeen(storageKey);
  const existing = seen[questionId];
  if (typeof existing === "number") return existing;

  seen[questionId] = now;
  try {
    window.localStorage.setItem(storageKey, JSON.stringify(seen));
  } catch {
    // Private mode, quota, disabled storage. The returned timestamp is still correct
    // for this page load; only surviving a reload is lost.
  }

  return now;
}

/**
 * Submits one answer.
 *
 * **The in-flight guard is not defensive tidiness.** Two fast taps on a phone against a
 * closing question is the ordinary thing to do, and the second request would come back
 * `already-answered` — telling the attendee their own accepted answer was refused. The
 * join button carries the same guard for the same reason.
 *
 * The response deliberately carries no verdict, so there is nothing to return but
 * whether it landed.
 */
let inFlight = false;

export async function submitAnswer(
  playerId: string,
  questionId: string,
  optionIds: readonly string[],
  elapsedMs: number
): Promise<SubmitOutcome> {
  if (inFlight) return { outcome: "failed" };
  inFlight = true;

  const body = new FormData();
  body.set("playerId", playerId);
  body.set("questionId", questionId);
  body.set("elapsedMs", String(Math.round(elapsedMs)));
  // Repeated field, so a multiple-choice answer needs no encoding scheme.
  for (const id of optionIds) body.append("optionIds", id);

  try {
    const response = await fetch("/api/quiz/answer", { method: "POST", body });
    if (response.ok) return { outcome: "accepted" };

    const payload = (await response.json().catch(() => ({}))) as { error?: string };
    return payload.error
      ? { outcome: "rejected", error: payload.error }
      : { outcome: "failed" };
  } catch {
    return { outcome: "failed" };
  } finally {
    inFlight = false;
  }
}

/**
 * Fetches this device's own result for a revealed question.
 *
 * Returns `null` on any failure, and the view must degrade to the correct answer it
 * already has from the snapshot rather than showing an error. That split — correctness
 * in the broadcast, the award per device — is the reason the design carries the ids in
 * the snapshot at all, so a failure here should cost the attendee their score line and
 * nothing else.
 */
export async function fetchResult(playerId: string, questionId: string): Promise<OwnResult | null> {
  const body = new FormData();
  body.set("playerId", playerId);
  body.set("questionId", questionId);

  try {
    const response = await fetch("/api/quiz/result", { method: "POST", body });
    if (!response.ok) return null;

    const payload = (await response.json().catch(() => null)) as OwnResult | null;
    if (payload === null || typeof payload.answered !== "boolean") return null;

    return payload;
  } catch {
    return null;
  }
}
